/* eslint-disable */
/* prettier-ignore */
// generated by: UnPlugin-Vue-Components
// read more: https://github.com/vuejs/core/pull/3399

export {};

declare module 'vue' {
	export interface GlobalComponents {
		BackGround: typeof import('./src/components/BackGround.vue')['default'];
		UpLoad: typeof import('./src/components/UpLoad.vue')['default'];
	}
}